[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 '-DCOLDSAFE_DEVICE_ID="esp32-lab-01"'
lib_deps =
    beegee-tokyo/DHT sensor library for ESPx@1.19
    256dpi/MQTT@2.5.3

[env:esp32dev-02]
extends = env:esp32dev
build_flags = -std=gnu++17 '-DCOLDSAFE_DEVICE_ID="esp32-lab-02"'
